### ISSUE TITLE
Не работает выдача домашек

### ISSUE THREAD

**Issue by pressfswearing** [xD1rty/dnevniklib#7]
![image](https://github.com/xD1rty/dnevniklib/assets/145866484/50a791f4-7522-4439-9091-2352e251ae70)
пытаюсь получить домашнюю работу, даёт такую ошибку

**Comment by pressfswearing** [comment]
каким образом я могу это сделать?

**Comment by xD1rty** [comment]
> каким образом я могу это сделать?

homework = Homework(Student(token))
и да, я для домашки не написал документацию, там есть нюанс

**Comment by pressfswearing** [comment]
> > каким образом я могу это сделать?
> 
> homework = Homework(Student(token)) и да, я для домашки не написал документацию, там есть нюанс

понял, что за нюанс?

**Comment by xD1rty** [comment]
> > > каким образом я могу это сделать?
> > 
> > homework = Homework(Student(token)) и да, я для домашки не написал документацию, там есть нюанс
> 
> понял, что за нюанс?

связанный с датой, там дневник принимает свой формат даты. так что на выходных решим все вопросы и ответим тебе
