### ISSUE TITLE
Как получить токен?

### ISSUE THREAD

**Issue by jilotta** [xD1rty/dnevniklib#8]
Собственно, сабж. Конструктор ученика просит Auth-Token, как можно его получить?

**Comment by xd2dd** [comment]
Привет. Перейдите в Cookies на странице дневника и найдите auth-token. Это и будет токеном соответственно

**Comment by jilotta** [comment]
Это понятно, а можно ли его получить изнутри АПИ, чтобы каждый раз из браузера новый токен не копировать?

**Comment by xd2dd** [comment]
Апи Меша не предоставляет данный функционал или я еще не все нашел

**Comment by jilotta** [comment]
По идее должен предоставлять, токен же откуда-то берется. Удачи!

**Comment by xd2dd** [comment]
токен берется из статичной страницы mos.ru, соответственно простым запросом его не так уж и легко достать

**Comment by jilotta** [comment]
Понятно, спасибо! Буду искать способ)

**Comment by AlexanderMatveev** [comment]
Теперь на одной куке не работает, я шлю все куки
